name: environment_OCG_Saildrone
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cartopy
  - seawater
  - numpy
  - pandas
  - matplotlib
  - pip
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - jupytext
  - pip:
    - PyCO2SYS
    - ipynb
